name: Update GitHub README Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options:
            username=${{ github.repository_owner }}&show_icons=true&rank_icon=github&hide_border=true&theme=github_dark
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Top languages
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&hide_border=true&theme=github_dark
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Pinned repo 1
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=caculate-score&show_owner=true&hide_border=true&theme=github_dark
          path: profile/pinned-1.svg
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Pinned repo 2
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=Blade&show_owner=true&hide_border=true&theme=github_dark
          path: profile/pinned-2.svg
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add profile/*.svg
          git commit -m "update github readme stats" || exit 0
          git push
